### ISSUE TITLE
Login Auth

### ISSUE THREAD

**Issue by Jbithell** [adam-rms/adam-rms-v2#9]

**Comment by Robert-Watts** [comment]
@Jbithell I have created a branch "[auth](https://github.com/adam-rms/adam-rms-v2/compare/auth)" where I have attempted to implement this. It is somewhat copied and pasted from v1 app. Because the Backend returns to attempting to open the app I cannot test the full flow of the auth. This is isuue marked backend so were there changes that were needed on the server to make this better? 

If you are going to do the ticket feel free to completely disregard the code I have written

**Comment by Jbithell** [comment]
What would you need to be able to get the full flow working @Robert-Watts?

**Comment by Robert-Watts** [comment]
@Jbithell Theoretically it works, i have just not been able to test it. Basically because the backend returns a callback which is designed to open the app rather than a proper oauth return I cannot test it locally (without copying the token into app storage myself). i have attempted to build it and run it on my phone to test it but while the build succeeds the app crashes on the splash screen. To be honest I am at a bit of a loss as to where to go next with testing it.

**Comment by Robert-Watts** [comment]
https://github.com/adam-rms/adam-rms/blob/8f99d4ec9e44c4a0df9c1f024c0c755d08902ab2/html/admin/login/index.php#L8 that section there is the bit thats triggering it to open the app

**Comment by Jbithell** [comment]
Is there a way to tell your request not to follow redirects?

**Comment by cherry-john** [comment]
Closed with #39
